INSERT INTO HOUSE_DOMAIN(ADDRESS)
VALUES
('123 MADEUPLANE'),
('321 FAKESTREET');






INSERT INTO CAT_DOMAIN (AGE,NAME,SPEECH_VOLUME,MY_HOUSE_ID)
VALUES
(10,'CATNAME',11.5,1),
(5,'NAMECAT',6,1),
(8,'RAVI',10,1);